language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pip install google-compute-engine
  - pip install pytest==5.0.1
  - pip install pytest-cov==2.7.1
  - pip install -e .
  - pytest --cov=fancy_nlp tests/
after_success:
  - coveralls
